# Generated by Django 5.2.11 on 2026-03-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_function_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SEMED_ADMIN', 'SEMED Admin'), ('MUNICIPAL_MANAGER', 'Gestor Municipal'), ('NUTRITIONIST', 'Nutricionista'), ('SCHOOL_FEEDING_COORDINATOR', 'Coordenador de Alimentacao Escolar'), ('SCHOOL_DIRECTOR', 'Diretor Escolar'), ('SCHOOL_OPERATOR', 'Merendeira / Apoio Operacional'), ('CAE_COUNCILOR', 'Conselheiro do CAE'), ('STOCK_OPERATOR', 'Tecnico de Estoque/Compras')], default='SEMED_ADMIN', max_length=32),
        ),
    ]
