# Generated by Django 5.2.11 on 2026-04-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
        ('schools', '0003_municipality_school_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.municipality'),
        ),
    ]
