[pytest]
DJANGO_SETTINGS_MODULE = merenda_semed.settings
python_files = tests.py test_*.py *_tests.py
testpaths =
    accounts
    auditlog
    inventory
    menus
    pnae
    production
    public
    recipes
    schools
    tests
addopts = -q
