# Generated by Django 5.1.5 on 2026-02-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_menu_author_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calc_mode',
            field=models.CharField(choices=[('FREE_TEXT', 'Texto livre'), ('RECIPE', 'Receita')], default='FREE_TEXT', max_length=20),
        ),
    ]
