# Generated by Django 5.2.11 on 2026-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_menuitem_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='nutritional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
