# Generated by Django 5.2.11 on 2026-04-05 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_educationmodality_educationstage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'state'],
                'constraints': [models.UniqueConstraint(fields=('name', 'state'), name='unique_municipality_name_state'), models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='unique_municipality_code')],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.municipality'),
        ),
    ]
