# Generated by Django 5.1.5 on 2026-02-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_delivery_conference_signed_by'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='schools.school')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_balances', to='inventory.supply')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'supply'), name='unique_school_supply_balance')],
            },
        ),
    ]
