# Generated by Django 5.2.11 on 2026-02-08 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_responsible_delivery_receiver_signature_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstockbalance',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Limite mínimo de estoque para esta escola', max_digits=12),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DELIVERY_CONFERRED', 'Entrega Conferida'), ('DELIVERY_WITH_NOTE', 'Entrega com Observação'), ('DELIVERY_DIVERGENCE', 'Divergência na Entrega')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.delivery')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
