# Generated by Django 5.1.5 on 2026-02-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_supplier_supplierreceipt_supplierreceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='nova_classification',
            field=models.CharField(blank=True, choices=[('IN_NATURA', 'In natura ou minimamente processados'), ('CULINARIOS', 'Ingredientes culinários processados'), ('PROCESSADOS', 'Alimentos processados'), ('ULTRAPROCESSADOS', 'Alimentos ultraprocessados')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supply',
            name='nutritional_function',
            field=models.CharField(blank=True, choices=[('CONSTRUTORES', 'Alimentos Construtores'), ('ENERGETICOS', 'Alimentos Energéticos'), ('REGULADORES', 'Alimentos Reguladores'), ('ENERGETICOS_EXTRAS', 'Alimentos Energéticos Extras')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='supply',
            name='category',
            field=models.CharField(blank=True, default='Outros', max_length=100),
        ),
    ]
