# Generated by Django 5.1.5 on 2026-02-25 14:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supply_nova_nutritional'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='storage_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DELIVERY_CONFERRED', 'Entrega Conferida'), ('DELIVERY_WITH_NOTE', 'Entrega com Observação'), ('DELIVERY_DIVERGENCE', 'Divergência na Entrega'), ('LOT_EXPIRING_SOON', 'Lote Próximo do Vencimento'), ('LOT_EXPIRED', 'Lote Vencido')], max_length=30),
        ),
        migrations.CreateModel(
            name='SupplierReceiptItemLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(max_length=120)),
                ('expiry_date', models.DateField()),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('divergence_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.supplierreceiptitem')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_receipt_item_lots', to='inventory.supply')),
            ],
            options={
                'ordering': ['expiry_date', 'lot_code'],
            },
        ),
        migrations.CreateModel(
            name='SupplyLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(max_length=120)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('storage_instructions_snapshot', models.TextField(blank=True, default='')),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('BLOCKED', 'Bloqueado'), ('EXPIRED', 'Vencido'), ('DISCARDED', 'Descartado')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_lots', to='inventory.supplier')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.supply')),
            ],
            options={
                'ordering': ['expiry_date', 'lot_code'],
            },
        ),
        migrations.CreateModel(
            name='LotBalanceSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_balances', to='schools.school')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_balances', to='inventory.supplylot')),
            ],
        ),
        migrations.CreateModel(
            name='LotBalanceCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='central_balance', to='inventory.supplylot')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItemLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('divergence_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.deliveryitem')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_item_lots', to='inventory.supplylot')),
            ],
            options={
                'ordering': ['lot__expiry_date', 'lot__lot_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplylot',
            constraint=models.UniqueConstraint(fields=('supply', 'lot_code', 'expiry_date'), name='unique_supply_lot_code_expiry'),
        ),
        migrations.AddConstraint(
            model_name='lotbalanceschool',
            constraint=models.UniqueConstraint(fields=('school', 'lot'), name='unique_school_lot_balance'),
        ),
        migrations.AddConstraint(
            model_name='deliveryitemlot',
            constraint=models.UniqueConstraint(fields=('delivery_item', 'lot'), name='unique_lot_per_delivery_item'),
        ),
    ]
