# Generated by Django 5.2.11 on 2026-03-01 01:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_supply_storage_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviado'), ('CONFERRED', 'Conferido'), ('FINALIZED', 'Finalizada')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='DeliveryNutritionistSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('crn', models.CharField(blank=True, max_length=80)),
                ('function_role', models.CharField(blank=True, max_length=100)),
                ('signature_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionist_signatures', to='inventory.delivery')),
            ],
        ),
    ]
