# Generated by Django 5.2.11 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviado'), ('IN_CONFERENCE', 'Em Conferencia'), ('CONFERRED', 'Conferido'), ('FINALIZED', 'Finalizada')], default='DRAFT', max_length=16),
        ),
    ]
