# Generated by Django 5.2.11 on 2026-03-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_created_320ace_idx',
            old_name='auditlog_aud_created_5f5082_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_user_id_4cf170_idx',
            old_name='auditlog_aud_user_id_019e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_action__ef1bd4_idx',
            old_name='auditlog_aud_action__3199b9_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='auditlog_au_method_211b71_idx',
            old_name='auditlog_aud_method_f07c53_idx',
        ),
    ]
