# Generated by Django 5.1.5 on 2026-02-24 15:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_supply_nova_nutritional'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCalculatorLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_scope', models.CharField(choices=[('MENU_WEEK', 'Menu semanal'), ('MENU_DAY', 'Menu por dia'), ('RECIPE_ONLY', 'Somente receita')], default='MENU_WEEK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_calculator_links', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='inventory.supply')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='SupplyConsumptionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(blank=True, default='', max_length=30)),
                ('qty_per_student', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('g', 'g'), ('l', 'L'), ('ml', 'ml'), ('unit', 'Unit')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_rules', to='schools.school')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_rules', to='inventory.supply')),
            ],
            options={
                'ordering': ['school__name', 'supply__name', 'meal_type'],
                'constraints': [models.UniqueConstraint(fields=('school', 'supply', 'meal_type'), name='unique_rule_school_supply_meal')],
            },
        ),
    ]
