# Generated by Django 5.1.5 on 2026-02-24 15:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_supply_nova_nutritional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('servings_base', models.PositiveIntegerField(default=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('g', 'g'), ('l', 'L'), ('ml', 'ml'), ('unit', 'Unit')], max_length=10)),
                ('optional', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='inventory.supply')),
            ],
            options={
                'ordering': ['supply__name'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'supply'), name='unique_recipe_supply_ingredient')],
            },
        ),
    ]
