# Generated by Django 5.2.11 on 2026-03-30 14:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0002_recipe_equipment_notes_recipe_portion_weight_and_more'),
        ('schools', '0002_educationmodality_educationstage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PnaeAnnualPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('justification', models.TextField(blank=True, default='')),
                ('diagnosis_summary', models.TextField(blank=True, default='')),
                ('general_objectives', models.TextField(blank=True, default='')),
                ('operational_strategy', models.TextField(blank=True, default='')),
                ('execution_locations', models.TextField(blank=True, default='')),
                ('executing_agency', models.CharField(blank=True, default='', max_length=255)),
                ('financial_schedule_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_REVIEW', 'Em revisao'), ('APPROVED', 'Aprovado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pnae_annual_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pnae_annual_plans', to=settings.AUTH_USER_MODEL)),
                ('responsible_nutritionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_pnae_annual_plans', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnae_annual_plans', to='schools.school')),
            ],
            options={
                'ordering': ['-year', 'school__name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PnaeAnnualAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('responsible_sector', models.CharField(blank=True, default='', max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planejada'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluida'), ('CANCELLED', 'Cancelada')], default='PLANNED', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pnae.pnaeannualplan')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PnaeAnnualBudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('funding_source', models.CharField(blank=True, default='', max_length=160)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('executed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='pnae.pnaeannualplan')),
            ],
            options={
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='PnaeAnnualEvaluationTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(blank=True, default='', max_length=120)),
                ('target_audience', models.CharField(blank=True, default='', max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_tools', to='pnae.pnaeannualplan')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PnaeAnnualGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('indicator', models.CharField(blank=True, default='', max_length=255)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='pnae.pnaeannualplan')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PnaeAnnualScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('activity', models.CharField(max_length=255)),
                ('expected_result', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='pnae.pnaeannualplan')),
            ],
            options={
                'ordering': ['month', 'order', 'activity'],
            },
        ),
        migrations.CreateModel(
            name='PnaeAnnualPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('meal_type', models.CharField(choices=[('BREAKFAST1', 'Desjejum'), ('SNACK1', 'Lanche'), ('LUNCH', 'Almoco'), ('SNACK2', 'Lanche'), ('BREAKFAST2', 'Desjejum'), ('DINNER_COFFEE', 'Cafe da noite'), ('BREAKFAST', 'Cafe (legado)'), ('SNACK', 'Lanche (legado)')], max_length=16)),
                ('servings_planned', models.PositiveIntegerField(default=0)),
                ('weekly_frequency', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pnae_plan_items', to='schools.educationmodality')),
                ('education_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pnae_plan_items', to='schools.educationstage')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pnae.pnaeannualplan')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pnae_plan_items', to='recipes.recipe')),
            ],
            options={
                'ordering': ['month', 'education_stage__name', 'meal_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='pnaeannualplan',
            constraint=models.UniqueConstraint(fields=('school', 'year'), name='unique_pnae_annual_plan_per_school_year'),
        ),
        migrations.AddConstraint(
            model_name='pnaeannualplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'education_stage', 'education_modality', 'month', 'meal_type'), name='unique_pnae_plan_item_scope'),
        ),
    ]
