# Generated by Django 5.2.11 on 2026-04-05 19:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnae', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pnaeannualplan',
            name='last_review_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pnaeannualplan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pnaeannualplan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_pnae_annual_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pnaeannualplan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pnaeannualplan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_pnae_annual_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pnaeannualplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_REVIEW', 'Em revisao'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='pnaeannualplanitem',
            name='weekly_frequency',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.CreateModel(
            name='PnaeAnnualPlanWorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Criado'), ('SUBMITTED', 'Submetido para revisao'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado'), ('REOPENED', 'Reaberto'), ('ARCHIVED', 'Arquivado'), ('UPDATED', 'Atualizado')], max_length=20)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Rascunho'), ('IN_REVIEW', 'Em revisao'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado'), ('ARCHIVED', 'Arquivado')], default='', max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_REVIEW', 'Em revisao'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado'), ('ARCHIVED', 'Arquivado')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pnae_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='pnae.pnaeannualplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PnaeAnnualPlanMonthlyExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Nao iniciada'), ('IN_PROGRESS', 'Em andamento'), ('PARTIAL', 'Parcial'), ('COMPLETED', 'Concluida'), ('BLOCKED', 'Bloqueada')], default='NOT_STARTED', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('planned_servings', models.PositiveIntegerField(default=0)),
                ('executed_servings', models.PositiveIntegerField(default=0)),
                ('execution_notes', models.TextField(blank=True, default='')),
                ('deviation_notes', models.TextField(blank=True, default='')),
                ('evidence_links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pnae_monthly_executions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_executions', to='pnae.pnaeannualplan')),
            ],
            options={
                'ordering': ['month'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'month'), name='unique_pnae_monthly_execution_per_plan_month')],
            },
        ),
    ]
