# Generated by Django 5.2.11 on 2026-04-06 18:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_menu_nutritional_info'),
        ('pnae', '0002_pnaeannualplan_last_review_comment_and_more'),
        ('recipes', '0002_recipe_equipment_notes_recipe_portion_weight_and_more'),
        ('schools', '0003_municipality_school_municipality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PnaeAcceptabilityTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('HEDONIC', 'Escala hedônica'), ('LUDIC', 'Cartelas lúdicas'), ('REST_INGESTION', 'Resto-ingestão'), ('WITHIN_OUTSIDE', 'Dentro-fora do padrão')], max_length=20)),
                ('objective', models.CharField(choices=[('NEW_OR_ATYPICAL', 'Preparação/alimento novo ou atípico'), ('RECURRING_MENU', 'Cardápio praticado frequentemente'), ('PROCUREMENT_SAMPLE', 'Amostra para aquisição')], max_length=24)),
                ('analysis_scope', models.CharField(choices=[('PREPARATION', 'Preparação'), ('MENU', 'Cardápio/refeição'), ('PRODUCT', 'Produto/amostra')], max_length=16)),
                ('service_mode', models.CharField(choices=[('CAFETERIA', 'Refeitório'), ('CLASSROOM', 'Sala de aula'), ('SELF_SERVICE', 'Autosserviço'), ('PROCUREMENT_PANEL', 'Equipe de provadores')], max_length=20)),
                ('preparation_name', models.CharField(max_length=255)),
                ('target_group', models.CharField(blank=True, default='', max_length=255)),
                ('classes_sampled', models.TextField(blank=True, default='')),
                ('test_date', models.DateField(default=django.utils.timezone.localdate)),
                ('weekday_label', models.CharField(blank=True, default='', max_length=32)),
                ('weather_context', models.CharField(blank=True, default='', max_length=120)),
                ('serving_time', models.CharField(blank=True, default='', max_length=120)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('eligible_students_count', models.PositiveIntegerField(blank=True, null=True)),
                ('adhered_students_count', models.PositiveIntegerField(blank=True, null=True)),
                ('loved_count', models.PositiveIntegerField(default=0)),
                ('liked_count', models.PositiveIntegerField(default=0)),
                ('indifferent_count', models.PositiveIntegerField(default=0)),
                ('disliked_count', models.PositiveIntegerField(default=0)),
                ('hated_count', models.PositiveIntegerField(default=0)),
                ('within_count', models.PositiveIntegerField(default=0)),
                ('outside_count', models.PositiveIntegerField(default=0)),
                ('prepared_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leftover_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plate_waste_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('non_edible_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distributed_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('minimum_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rejection_index', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('acceptance_index', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('adhesion_index', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('adhesion_classification', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Média'), ('LOW', 'Baixa'), ('VERY_LOW', 'Muito baixa'), ('NOT_INFORMED', 'Não informada')], default='NOT_INFORMED', max_length=16)),
                ('approved', models.BooleanField(default=False)),
                ('next_retest_date', models.DateField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('positive_feedback', models.TextField(blank=True, default='')),
                ('negative_feedback', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_acceptability_tests', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptability_tests', to='menus.menu')),
                ('previous_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retests', to='pnae.pnaeacceptabilitytest')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptability_tests', to='recipes.recipe')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptability_tests', to='schools.school')),
            ],
            options={
                'ordering': ['-test_date', '-created_at'],
            },
        ),
    ]
