# Generated by Django 5.2.11 on 2026-04-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnae', '0003_pnaeacceptabilitytest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnaeacceptabilitytest',
            name='respondent_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pnaeacceptabilitytest',
            name='respondent_profile',
            field=models.CharField(choices=[('NOT_INFORMED', 'Nao informado'), ('STUDENT', 'Aluno'), ('PROFESSIONAL', 'Profissional')], default='NOT_INFORMED', max_length=16),
        ),
    ]
